<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = '__root__';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'beberlei/assert' => 'v3.3.2@cb70015c04be1baee6f5f5c953703347c0ac1655',
  'brick/math' => '0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae',
  'composer/package-versions-deprecated' => '1.11.99.4@b174585d1fe49ceed21928a945138948cb394600',
  'doctrine/annotations' => '1.14.3@fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
  'doctrine/cache' => '1.13.0@56cd022adb5514472cb144c087393c1821911d09',
  'doctrine/collections' => '1.8.0@2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
  'doctrine/common' => '2.13.3@f3812c026e557892c34ef37f6ab808a6b567da7f',
  'doctrine/dbal' => '2.13.9@c480849ca3ad6706a39c970cdfe6888fa8a058b8',
  'doctrine/deprecations' => 'v1.1.1@612a3ee5ab0d5dd97b7cf3874a6efe24325efac3',
  'doctrine/doctrine-bundle' => '2.3.2@d6b3c37804539a24ba8a7d647a6144cab2f13242',
  'doctrine/doctrine-migrations-bundle' => '2.2.3@0a081b55a88259a887af7be654743a8c5f703e99',
  'doctrine/event-manager' => '1.2.0@95aa4cb529f1e96576f3fda9f5705ada4056a520',
  'doctrine/inflector' => '1.4.4@4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
  'doctrine/instantiator' => '1.5.0@0a0fa9780f5d4e507415a065172d26a98d02047b',
  'doctrine/lexer' => '1.2.3@c268e882d4dbdd85e36e4ad69e02dc284f89d229',
  'doctrine/migrations' => '2.3.5@28d92a34348fee5daeb80879e56461b2e862fc05',
  'doctrine/orm' => '2.7.5@01187c9260cd085529ddd1273665217cae659640',
  'doctrine/persistence' => '1.3.8@7a6eac9fb6f61bba91328f15aa7547f4806ca288',
  'doctrine/reflection' => '1.2.3@1034e5e71f89978b80f9c1570e7226f6c3b9b6fb',
  'doctrine/sql-formatter' => '1.1.3@25a06c7bf4c6b8218f47928654252863ffc890a5',
  'egulias/email-validator' => '3.2.6@e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
  'firebase/php-jwt' => 'v6.4.0@4dd1e007f22a927ac77da5a3fbb067b42d3bc224',
  'friendsofphp/proxy-manager-lts' => 'v1.0.16@ecadbdc9052e4ad08c60c8a02268712e50427f7c',
  'google/apiclient' => 'v2.14.0@789c8b07cad97f420ac0467c782036f955a2ad89',
  'google/apiclient-services' => 'v0.302.0@ac872f59a7b4631b12628fe990c167d18a71c783',
  'google/auth' => 'v1.26.0@f1f0d0319e2e7750ebfaa523c78819792a9ed9f7',
  'google/cloud' => 'v0.171.1@f72a440af76b0efd32f3939816da12c0c32b8dbf',
  'google/common-protos' => '1.4.0@b1ee63636d94fe88f6cff600a0f23fae06b6fa2e',
  'google/crc32' => 'v0.1.0@a8525f0dea6fca1893e1bae2f6e804c5f7d007fb',
  'google/gax' => 'v1.19.1@30f6b307faa9858bf58d967664467098dbbc354f',
  'google/grpc-gcp' => 'v0.2.1@899d0112812a812df7692617a59f4076f0d01719',
  'google/longrunning' => 'v0.2.6@9689b4db54cf4cf8186118d9d59aa9ba35bb5842',
  'google/protobuf' => 'v3.23.3@e611e00ffc99123fcbddc77774f26c813ead9294',
  'grpc/grpc' => '1.52.0@98394cd601a587ca68294e6209bd713856969105',
  'guzzlehttp/guzzle' => '7.7.0@fb7566caccf22d74d1ab270de3551f72a58399f5',
  'guzzlehttp/promises' => '1.5.3@67ab6e18aaa14d753cc148911d273f6e6cb6721e',
  'guzzlehttp/psr7' => '2.4.5@0454e12ef0cd597ccd2adb036f7bda4e7fface66',
  'jms/metadata' => '2.8.0@7ca240dcac0c655eb15933ee55736ccd2ea0d7a6',
  'knplabs/knp-components' => 'v2.5.1@ab7ced8a662e6aa1898b5c4919fe3eb78d62d963',
  'knplabs/knp-paginator-bundle' => 'v5.3.0@87ca999b6ac886e3f20a1e3abc07523140509ca4',
  'laminas/laminas-code' => '3.4.1@1cb8f203389ab1482bf89c0e70a04849bacd7766',
  'laminas/laminas-eventmanager' => '3.2.1@ce4dc0bdf3b14b7f9815775af9dfee80a63b4748',
  'laminas/laminas-zendframework-bridge' => '1.1.1@6ede70583e101030bcace4dcddd648f760ddf642',
  'lcobucci/jwt' => '3.4.6@3ef8657a78278dfeae7707d51747251db4176240',
  'monolog/monolog' => '2.9.1@f259e2b15fb95494c83f52d3caad003bbf5ffaa1',
  'paragonie/constant_time_encoding' => 'v2.6.3@58c3f47f650c94ec05a151692652a868995d2938',
  'phpdocumentor/reflection-common' => '2.2.0@1d01c49d4ed62f25aa84a747ad35d5a16924662b',
  'phpdocumentor/reflection-docblock' => '5.3.0@622548b623e81ca6d78b721c5e029f4ce664f170',
  'phpdocumentor/type-resolver' => '1.6.1@77a32518733312af16a44300404e945338981de3',
  'phpseclib/phpseclib' => '3.0.20@543a1da81111a0bfd6ae7bbc2865c5e89ed3fc67',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.1.1@8622567409010282b7aeebe4bb841fe98b58dcaf',
  'psr/http-client' => '1.0.2@0955afe48220520692d2d09f7ab7e0f93ffd6a31',
  'psr/http-factory' => '1.0.2@e616d01114759c4c489f93b099585439f795fe35',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.4@d49695b909c3b7628b6289db5479a1c204601f11',
  'ralouphie/getallheaders' => '3.0.3@120b605dfeb996808c31b6477290a714d356e822',
  'ramsey/collection' => '1.1.4@ab2237657ad99667a5143e32ba2683c8029563d4',
  'ramsey/uuid' => '4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df',
  'rize/uri-template' => '0.3.5@5ed4ba8ea34af84485dea815d4b6b620794d1168',
  'scheb/two-factor-bundle' => 'v4.18.4@78f5832d59ec49491ef27edc0fa03a3110139f5c',
  'sendinblue/api-v3-sdk' => 'v8.4.2@5d08398c7247a2f5d80f285d08a6dbe169f18eab',
  'sensio/framework-extra-bundle' => 'v5.6.1@430d14c01836b77c28092883d195a43ce413ee32',
  'spomky-labs/otphp' => 'v10.0.3@9784d9f7c790eed26e102d6c78f12c754036c366',
  'symfony/apache-pack' => 'v1.0.1@3aa5818d73ad2551281fc58a75afd9ca82622e6c',
  'symfony/asset' => 'v4.4.46@6ef0f9f352f90c469e8b363ebc038d81a7198873',
  'symfony/cache' => 'v5.4.23@983c79ff28612cdfd66d8e44e1a06e5afc87e107',
  'symfony/cache-contracts' => 'v2.5.2@64be4a7acb83b6f2bf6de9a02cee6dad41277ebc',
  'symfony/config' => 'v5.4.21@2a6b1111d038adfa15d52c0871e540f3b352d1e4',
  'symfony/console' => 'v4.4.49@33fa45ffc81fdcc1ca368d4946da859c8cdb58d9',
  'symfony/debug' => 'v4.4.44@1a692492190773c5310bc7877cb590c04c2f05be',
  'symfony/dependency-injection' => 'v5.4.24@4645e032d0963fb614969398ca28e47605b1a7da',
  'symfony/deprecation-contracts' => 'v2.5.2@e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
  'symfony/doctrine-bridge' => 'v4.4.48@8dbbec53714eb512321380d582b45ff7e074a5d6',
  'symfony/dotenv' => 'v4.4.37@fcedd6d382b3afc3e1e786aa4e4fc4cf06f564cf',
  'symfony/error-handler' => 'v4.4.44@be731658121ef2d8be88f3a1ec938148a9237291',
  'symfony/event-dispatcher' => 'v4.4.44@1e866e9e5c1b22168e0ce5f0b467f19bba61266a',
  'symfony/event-dispatcher-contracts' => 'v1.1.13@1d5cd762abaa6b2a4169d3e77610193a7157129e',
  'symfony/expression-language' => 'v4.4.47@e4964c7636e19f6008660f450c09121c80c2a7b9',
  'symfony/filesystem' => 'v4.4.42@815412ee8971209bd4c1eecd5f4f481eacd44bf5',
  'symfony/finder' => 'v4.4.44@66bd787edb5e42ff59d3523f623895af05043e4f',
  'symfony/flex' => 'v1.20.0@49059a10127ac8270957e116a2251ae535d202ac',
  'symfony/form' => 'v4.4.48@e1d137b13e0ec2cb5c5e38debca7a510c6f858c6',
  'symfony/framework-bundle' => 'v4.4.49@d8cf2558249004a29b8e27b1f6eae52337ff471b',
  'symfony/google-mailer' => 'v4.4.41@feb32d9ce8656a5accd950fd8c22e3c4fdf97656',
  'symfony/http-client' => 'v4.4.49@0185497cd61440bdf68df7d81241b97a543e9c3f',
  'symfony/http-client-contracts' => 'v2.5.2@ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
  'symfony/http-foundation' => 'v4.4.49@191413c7b832c015bb38eae963f2e57498c3c173',
  'symfony/http-kernel' => 'v4.4.50@aa6df6c045f034aa13ac752fc234bb300b9488ef',
  'symfony/inflector' => 'v5.4.21@d56964e2b19253ba331a829c20d911dd27aa61b6',
  'symfony/intl' => 'v4.4.47@f1d0f9d91ab482d33423b788999fbb43c34a9a59',
  'symfony/mailer' => 'v4.4.49@554b8c0dc2db9d74e760fd6b726f527364f03302',
  'symfony/mime' => 'v5.4.13@bb2ccf759e2b967dcd11bdee5bdf30dddd2290bd',
  'symfony/monolog-bridge' => 'v5.2.12@2c3943d7c0100983f9c0a82807555273353e3539',
  'symfony/monolog-bundle' => 'v3.8.0@a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d',
  'symfony/options-resolver' => 'v5.4.21@4fe5cf6ede71096839f0e4b4444d65dd3a7c1eb9',
  'symfony/polyfill-intl-grapheme' => 'v1.27.0@511a08c03c1960e08a883f4cffcacd219b758354',
  'symfony/polyfill-intl-icu' => 'v1.27.0@a3d9148e2c363588e05abbdd4ee4f971f0a5330c',
  'symfony/polyfill-intl-idn' => 'v1.27.0@639084e360537a19f9ee352433b84ce831f3d2da',
  'symfony/polyfill-intl-normalizer' => 'v1.27.0@19bd1e4fcd5b91116f14d8533c57831ed00571b6',
  'symfony/polyfill-mbstring' => 'v1.27.0@8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
  'symfony/polyfill-php72' => 'v1.27.0@869329b1e9894268a8a61dabb69153029b7a8c97',
  'symfony/polyfill-php73' => 'v1.27.0@9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
  'symfony/polyfill-php80' => 'v1.27.0@7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
  'symfony/polyfill-php81' => 'v1.27.0@707403074c8ea6e2edaf8794b0157a0bfa52157a',
  'symfony/process' => 'v4.4.44@5cee9cdc4f7805e2699d9fd66991a0e6df8252a2',
  'symfony/property-access' => 'v4.4.44@d49682f6f0764df725c95128213a38f7e0a9f358',
  'symfony/property-info' => 'v4.4.49@971cf46634e44d93d2174cf004555b69b19c9487',
  'symfony/routing' => 'v5.4.22@c2ac11eb34947999b7c38fb4c835a57306907e6d',
  'symfony/security-bundle' => 'v4.4.50@076fd2088ada33d760758d98ff07ddedbf567946',
  'symfony/security-core' => 'v4.4.48@423ccb332784b236dfe6c5f396d0ac49db57c914',
  'symfony/security-csrf' => 'v5.2.12@f0af6689451582e55f6b3439362e72e536e916e4',
  'symfony/security-guard' => 'v4.4.46@f199eb1b19db11ce254b891580728c45a7ccacfd',
  'symfony/security-http' => 'v4.4.50@7fa4a0cac16f02cb534a6e9adcdb17385f94004f',
  'symfony/serializer' => 'v4.4.47@6e01d63c55657930a6de03d6e36aae50af98888d',
  'symfony/service-contracts' => 'v2.5.2@4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
  'symfony/stopwatch' => 'v4.4.46@757660703fbd139eea0001b759c6c3bf5bc3ea52',
  'symfony/string' => 'v5.4.22@8036a4c76c0dd29e60b6a7cafcacc50cf088ea62',
  'symfony/templating' => 'v4.4.44@2bfe94a5ebe0176612186e5f6b6a08a480c9e1f9',
  'symfony/translation' => 'v4.4.47@45036b1d53accc48fe9bab71ccd86d57eba0dd94',
  'symfony/translation-contracts' => 'v2.5.2@136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
  'symfony/twig-bridge' => 'v4.4.49@d6b0fbfd5e2fab79c0c7b8dfe579e47ee0999113',
  'symfony/twig-bundle' => 'v4.4.41@164c1edc69f2c7ee337323efc78a8a8a263f45ff',
  'symfony/validator' => 'v4.4.48@54781a4c41efbd283b779110bf8ae7f263737775',
  'symfony/var-dumper' => 'v5.4.24@8e12706bf9c68a2da633f23bfdc15b4dce5970b3',
  'symfony/var-exporter' => 'v5.4.21@be74908a6942fdd331554b3cec27ff41b45ccad4',
  'symfony/web-link' => 'v4.4.37@ab13621fd0c0119ad9ebc7179be7c5a1fc6a542d',
  'symfony/yaml' => 'v4.4.45@aeccc4dc52a9e634f1d1eebeb21eacfdcff1053d',
  'thecodingmachine/safe' => 'v1.3.3@a8ab0876305a4cdaef31b2350fcb9811b5608dbc',
  'twig/extra-bundle' => 'v3.6.1@802cc2dd46ec88285d6c7fa85c26ab7f2cd5bc49',
  'twig/twig' => 'v3.6.1@7e7d5839d4bec168dfeef0ac66d5c5a2edbabffd',
  'vich/uploader-bundle' => '1.15.0@07658fb47429d7e108fa43d8c74ca8cd7edaa0d9',
  'webmozart/assert' => '1.11.0@11cb2199493b2f8a3b53e7f19068fc6aac760991',
  'myclabs/deep-copy' => '1.11.1@7284c22080590fb39f2ffa3e9057f10a4ddd0e0c',
  'nikic/php-parser' => 'v4.15.5@11e2663a5bc9db5d714eedb4277ee300403b4a9e',
  'phar-io/manifest' => '2.0.3@97803eca37d319dfa7826cc2437fc020857acb53',
  'phar-io/version' => '3.2.1@4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
  'phpunit/php-code-coverage' => '7.0.15@819f92bba8b001d4363065928088de22f25a3a48',
  'phpunit/php-file-iterator' => '2.0.5@42c5ba5220e6904cbfe8b1a1bda7c0cfdc8c12f5',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '2.1.3@2454ae1765516d20c4ffe103d85a58a9a3bd5662',
  'phpunit/php-token-stream' => '3.1.3@9c1da83261628cb24b6a6df371b6e312b3954768',
  'phpunit/phpunit' => '8.5.33@7d1ff0e8c6b35db78ff13e3e05517d7cbf7aa32e',
  'sebastian/code-unit-reverse-lookup' => '1.0.2@1de8cd5c010cb153fcd68b8d0f64606f523f7619',
  'sebastian/comparator' => '3.0.5@1dc7ceb4a24aede938c7af2a9ed1de09609ca770',
  'sebastian/diff' => '3.0.4@6296a0c086dd0117c1b78b059374d7fcbe7545ae',
  'sebastian/environment' => '4.2.4@d47bbbad83711771f167c72d4e3f25f7fcc1f8b0',
  'sebastian/exporter' => '3.1.5@73a9676f2833b9a7c36968f9d882589cd75511e6',
  'sebastian/global-state' => '3.0.2@de036ec91d55d2a9e0db2ba975b512cdb1c23921',
  'sebastian/object-enumerator' => '3.0.4@e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2',
  'sebastian/object-reflector' => '1.1.2@9b8772b9cbd456ab45d4a598d2dd1a1bced6363d',
  'sebastian/recursion-context' => '3.0.1@367dcba38d6e1977be014dc4b22f47a484dac7fb',
  'sebastian/resource-operations' => '2.0.2@31d35ca87926450c44eae7e2611d45a7a65ea8b3',
  'sebastian/type' => '1.1.4@0150cfbc4495ed2df3872fb31b26781e4e077eb4',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'symfony/browser-kit' => 'v4.4.44@2a1ff40723ef6b29c8229a860a9c8f815ad7dbbb',
  'symfony/css-selector' => 'v4.4.44@bd0a6737e48de45b4b0b7b6fc98c78404ddceaed',
  'symfony/debug-bundle' => 'v4.4.37@f21cce588be146c9111cb9041f0784a6534fd648',
  'symfony/dom-crawler' => 'v5.4.23@4a286c916b74ecfb6e2caf1aa31d3fe2a34b7e08',
  'symfony/maker-bundle' => 'v1.39.1@30c8ac13511f6df7bc9ac088f31d7a48ce6433c6',
  'symfony/phpunit-bridge' => 'v5.4.23@1572c5b7cad812bdf0414d89a32a33a2dafb38ba',
  'symfony/web-profiler-bundle' => 'v4.4.47@c173202d8ce82fde63ec0953eaffdf065018b8f4',
  'theseer/tokenizer' => '1.2.1@34a41e998c2183e22995f158c581e7b5e755ab9e',
  'paragonie/random_compat' => '2.*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  'symfony/polyfill-ctype' => '*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  'symfony/polyfill-iconv' => '*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  'symfony/polyfill-php71' => '*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  'symfony/polyfill-php70' => '*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  'symfony/polyfill-php56' => '*@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
  '__root__' => 'dev-production@ec5067a651c40ab9e31a3fc81737d27c61d7c847',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!self::composer2ApiUsable()) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (self::composer2ApiUsable()) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }

    private static function composer2ApiUsable(): bool
    {
        if (!class_exists(InstalledVersions::class, false)) {
            return false;
        }

        if (method_exists(InstalledVersions::class, 'getAllRawData')) {
            $rawData = InstalledVersions::getAllRawData();
            if (count($rawData) === 1 && count($rawData[0]) === 0) {
                return false;
            }
        } else {
            $rawData = InstalledVersions::getRawData();
            if ($rawData === null || $rawData === []) {
                return false;
            }
        }

        return true;
    }
}
